import type { BuiltInFormFieldDefinition } from "@/lib/built-in-form/built-in-form-types";

/** 주최자가 「기본 신청폼 불러오기」로 사용할 수 있는 예시 항목 */
export const DEFAULT_BUILT_IN_FORM_FIELDS: BuiltInFormFieldDefinition[] = [
  {
    id: "fighter_name",
    label: "선수명",
    type: "text",
    source: "fighter.name",
    required: true,
    editable: false,
    displayOrder: 0,
  },
  {
    id: "fighter_birthDate",
    label: "생년월일",
    type: "date",
    source: "fighter.birthDate",
    required: true,
    editable: true,
    displayOrder: 1,
  },
  {
    id: "fighter_gender",
    label: "성별",
    type: "text",
    source: "fighter.gender",
    required: true,
    editable: false,
    displayOrder: 2,
  },
  {
    id: "fighter_phone",
    label: "연락처",
    type: "text",
    source: "fighter.phone",
    required: true,
    editable: true,
    displayOrder: 3,
  },
  {
    id: "gym_name",
    label: "체육관명",
    type: "text",
    source: "gym.name",
    required: true,
    editable: false,
    displayOrder: 4,
  },
  {
    id: "division",
    label: "신청 부문",
    type: "select",
    source: "application.division",
    required: true,
    editable: false,
    displayOrder: 5,
  },
  {
    id: "weight_class",
    label: "신청 체급",
    type: "text",
    source: "application.weightClass",
    required: false,
    editable: false,
    displayOrder: 6,
  },
  {
    id: "guardian_name",
    label: "보호자명",
    type: "text",
    source: "fighter.guardianName",
    required: false,
    editable: true,
    displayOrder: 7,
  },
  {
    id: "guardian_phone",
    label: "보호자 연락처",
    type: "text",
    source: "fighter.guardianPhone",
    required: false,
    editable: true,
    displayOrder: 8,
  },
  {
    id: "medical_note",
    label: "특이사항",
    type: "textarea",
    source: "manual",
    required: false,
    editable: true,
    displayOrder: 9,
  },
  {
    id: "athlete_consent",
    label: "선수 동의",
    type: "consentText",
    source: "athlete.consent",
    required: true,
    editable: false,
    displayOrder: 10,
  },
  {
    id: "guardian_consent",
    label: "보호자 동의",
    type: "consentText",
    source: "guardian.consent",
    required: "if_minor",
    editable: false,
    displayOrder: 11,
  },
  {
    id: "athlete_signature",
    label: "선수 서명",
    type: "signature",
    source: "athlete.signatureImage",
    required: true,
    editable: false,
    displayOrder: 12,
  },
  {
    id: "guardian_signature",
    label: "보호자 서명",
    type: "signature",
    source: "guardian.signatureImage",
    required: "if_minor",
    editable: false,
    displayOrder: 13,
  },
];

export const DEFAULT_BUILT_IN_FORM_TITLE = "기본 대회 신청폼";
