"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useTransition } from "react";
import {
  ensureBracketForDivisionAction,
  publishBracketFormAction,
  unpublishBracketFormAction,
} from "@/features/brackets/actions";
import { DivisionCompactDisplay } from "@/components/domain/shared/DivisionCompactDisplay";
import { Button, buttonVariants } from "@/components/ui/button";
import { BracketStatusBadge } from "@/components/domain/brackets/BracketStatusBadge";
import { BracketTypeBadge } from "@/components/domain/brackets/BracketTypeBadge";
import type { OrganizerBracketListItemVM } from "@/lib/services/bracket.service";
import { isAutoGeneratedBracketTitle } from "@/lib/event-division-fields";
import { organizerBracketTableWrapClass } from "@/lib/ui/organizer-bracket-ui";
import {
  listTableHeaderCellCenterClass,
  listTableHeaderCellStartClass,
  listTableHeaderRowClass,
} from "@/lib/ui/list-table-styles";
import { cn } from "@/lib/utils";
import { useAppConfirmDialog } from "@/components/shared/app-confirm-dialog";

function BracketDivisionCell({
  bracket,
}: {
  bracket: OrganizerBracketListItemVM;
}) {
  if (bracket.division) {
    return (
      <div className="min-w-0 space-y-1">
        <DivisionCompactDisplay
          division={bracket.division}
          mainClassName="text-base font-semibold leading-snug"
        />
        {!isAutoGeneratedBracketTitle(bracket.title) ? (
          <p className="text-muted-foreground text-xs">{bracket.title}</p>
        ) : null}
      </div>
    );
  }

  return (
    <div className="min-w-0 space-y-1">
      <p className="text-muted-foreground text-sm">경기구분 미지정</p>
      <p className="text-xs font-medium">{bracket.displayTitle}</p>
    </div>
  );
}

/** 목록은 인원수만. 명단은 관리 화면 SSOT. */
function UnmatchedCell({ bracket }: { bracket: OrganizerBracketListItemVM }) {
  return (
    <span
      className={cn(
        "tabular-nums",
        bracket.unmatchedCount === 0
          ? "text-muted-foreground"
          : "font-medium text-matchon-text-primary",
      )}
    >
      {bracket.unmatchedCount}명
    </span>
  );
}

function ManageBracketButton({
  eventId,
  bracket,
}: {
  eventId: string;
  bracket: OrganizerBracketListItemVM;
}) {
  const router = useRouter();
  const { alert } = useAppConfirmDialog();
  const [pending, startTransition] = useTransition();

  if (bracket.bracketId) {
    return (
      <Link
        href={`/organizer/events/${eventId}/brackets/${bracket.bracketId}`}
        className={cn(buttonVariants({ variant: "outline", size: "sm" }))}
      >
        관리
      </Link>
    );
  }

  return (
    <Button
      type="button"
      variant="outline"
      size="sm"
      disabled={pending}
      onClick={() => {
        startTransition(async () => {
          const fd = new FormData();
          fd.set("eventId", eventId);
          fd.set("divisionId", bracket.divisionId);
          const res = await ensureBracketForDivisionAction(fd);
          if (!res.ok) {
            await alert(res.error.message);
            return;
          }
          router.push(
            `/organizer/events/${eventId}/brackets/${res.data.bracketId}`,
          );
        });
      }}
    >
      {pending ? "준비 중…" : "관리"}
    </Button>
  );
}

function BracketActionButtons({
  eventId,
  bracket,
}: {
  eventId: string;
  bracket: OrganizerBracketListItemVM;
}) {
  return (
    <div className="flex flex-wrap justify-end gap-2">
      <ManageBracketButton eventId={eventId} bracket={bracket} />
      {bracket.bracketId && !bracket.isPublic ? (
        <form action={publishBracketFormAction}>
          <input type="hidden" name="bracketId" value={bracket.bracketId} />
          <Button size="sm" type="submit">
            공개
          </Button>
        </form>
      ) : null}
      {bracket.bracketId && bracket.isPublic ? (
        <form action={unpublishBracketFormAction}>
          <input type="hidden" name="bracketId" value={bracket.bracketId} />
          <Button size="sm" variant="secondary" type="submit">
            비공개
          </Button>
        </form>
      ) : null}
    </div>
  );
}

export function OrganizerBracketList({
  eventId,
  brackets,
}: {
  eventId: string;
  brackets: OrganizerBracketListItemVM[];
}) {
  return (
    <div className="space-y-4">
      <div className={cn(organizerBracketTableWrapClass, "hidden md:block")}>
        <table className="w-full min-w-[960px] text-left text-sm">
          <thead className={listTableHeaderRowClass}>
            <tr>
              <th className={cn(listTableHeaderCellStartClass, "px-4")}>
                경기구분 / 체급
              </th>
              <th className={cn(listTableHeaderCellStartClass, "px-4")}>
                방식
              </th>
              <th className={cn(listTableHeaderCellStartClass, "px-4")}>상태</th>
              <th className={cn(listTableHeaderCellStartClass, "px-4")}>공개</th>
              <th className={cn(listTableHeaderCellCenterClass, "px-4")}>
                경기 수
              </th>
              <th className={cn(listTableHeaderCellCenterClass, "px-4")}>
                미매칭
              </th>
              <th className={cn(listTableHeaderCellCenterClass, "px-4 text-right")}>
                동작
              </th>
            </tr>
          </thead>
          <tbody>
            {brackets.map((b) => (
              <tr
                key={b.id}
                className="border-b border-matchon-border/60 last:border-0 hover:bg-matchon-surface/50"
              >
                <td className="px-4 py-2.5 align-middle">
                  <BracketDivisionCell bracket={b} />
                </td>
                <td className="px-4 py-2.5 align-middle">
                  <BracketTypeBadge type={b.type} />
                </td>
                <td className="px-4 py-2.5 align-middle">
                  <BracketStatusBadge status={b.status} />
                </td>
                <td className="px-4 py-2.5 align-middle">
                  {b.isPublic ? "예" : "아니오"}
                </td>
                <td className="px-4 py-2.5 text-center align-middle">
                  {b.matchCount}
                </td>
                <td className="px-4 py-2.5 text-center align-middle">
                  <UnmatchedCell bracket={b} />
                </td>
                <td className="px-4 py-2.5 align-middle">
                  <BracketActionButtons eventId={eventId} bracket={b} />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="flex flex-col gap-3 md:hidden">
        {brackets.map((b) => (
          <div
            key={b.id}
            className="rounded-xl border border-matchon-border bg-white p-4 shadow-sm"
          >
            <div className="flex flex-wrap items-start justify-between gap-2">
              <BracketDivisionCell bracket={b} />
              <BracketStatusBadge status={b.status} />
            </div>
            <div className="flex flex-wrap gap-2">
              <BracketTypeBadge type={b.type} />
              <span className="text-muted-foreground text-xs">
                공개 {b.isPublic ? "예" : "아니오"} · 경기 {b.matchCount} · 미매칭{" "}
                {b.unmatchedCount}명
              </span>
            </div>
            <BracketActionButtons eventId={eventId} bracket={b} />
          </div>
        ))}
      </div>
    </div>
  );
}
