import Link from "next/link";
import {
  publishBracketFormAction,
  unpublishBracketFormAction,
} from "@/features/brackets/actions";
import { DivisionCompactDisplay } from "@/components/domain/shared/DivisionCompactDisplay";
import { Button, buttonVariants } from "@/components/ui/button";
import { BracketStatusBadge } from "@/components/domain/brackets/BracketStatusBadge";
import { BracketTypeBadge } from "@/components/domain/brackets/BracketTypeBadge";
import type { OrganizerBracketListItemVM } from "@/lib/services/bracket.service";
import { isAutoGeneratedBracketTitle } from "@/lib/event-division-fields";
import { organizerBracketTableWrapClass } from "@/lib/ui/organizer-bracket-ui";
import {
  listTableHeaderCellCenterClass,
  listTableHeaderCellStartClass,
  listTableHeaderRowClass,
} from "@/lib/ui/list-table-styles";
import { cn } from "@/lib/utils";

function BracketDivisionCell({
  bracket,
}: {
  bracket: OrganizerBracketListItemVM;
}) {
  if (bracket.division) {
    return (
      <div className="min-w-0 space-y-1">
        <DivisionCompactDisplay
          division={bracket.division}
          mainClassName="text-base font-semibold leading-snug"
        />
        {!isAutoGeneratedBracketTitle(bracket.title) ? (
          <p className="text-muted-foreground text-xs">{bracket.title}</p>
        ) : null}
      </div>
    );
  }

  return (
    <div className="min-w-0 space-y-1">
      <p className="text-muted-foreground text-sm">경기구분 미지정</p>
      <p className="text-xs font-medium">{bracket.displayTitle}</p>
    </div>
  );
}

export function OrganizerBracketList({
  eventId,
  brackets,
}: {
  eventId: string;
  brackets: OrganizerBracketListItemVM[];
}) {
  return (
    <div className="space-y-4">
      <div className={cn(organizerBracketTableWrapClass, "hidden md:block")}>
        <table className="w-full min-w-[880px] text-left text-sm">
          <thead className={listTableHeaderRowClass}>
            <tr>
              <th className={cn(listTableHeaderCellStartClass, "px-4")}>
                경기구분 / 체급
              </th>
              <th className={cn(listTableHeaderCellStartClass, "px-4")}>
                대진 방식
              </th>
              <th className={cn(listTableHeaderCellStartClass, "px-4")}>상태</th>
              <th className={cn(listTableHeaderCellStartClass, "px-4")}>공개</th>
              <th className={cn(listTableHeaderCellCenterClass, "px-4")}>
                경기 수
              </th>
              <th className={cn(listTableHeaderCellCenterClass, "px-4 text-right")}>
                동작
              </th>
            </tr>
          </thead>
          <tbody>
            {brackets.map((b) => (
              <tr
                key={b.id}
                className="border-b border-matchon-border/60 last:border-0 hover:bg-matchon-surface/50"
              >
                <td className="px-4 py-2.5">
                  <BracketDivisionCell bracket={b} />
                </td>
                <td className="px-4 py-2.5">
                  <BracketTypeBadge type={b.type} />
                </td>
                <td className="px-4 py-2.5">
                  <BracketStatusBadge status={b.status} />
                </td>
                <td className="px-4 py-2.5">{b.isPublic ? "예" : "아니오"}</td>
                <td className="px-4 py-2.5">{b.matchCount}</td>
                <td className="px-4 py-2.5">
                  <div className="flex flex-wrap justify-end gap-2">
                    <Link
                      href={`/organizer/events/${eventId}/brackets/${b.id}`}
                      className={cn(buttonVariants({ variant: "outline", size: "sm" }))}
                    >
                      관리
                    </Link>
                    {!b.isPublic ? (
                      <form action={publishBracketFormAction}>
                        <input type="hidden" name="bracketId" value={b.id} />
                        <Button size="sm" type="submit">
                          공개
                        </Button>
                      </form>
                    ) : (
                      <form action={unpublishBracketFormAction}>
                        <input type="hidden" name="bracketId" value={b.id} />
                        <Button size="sm" variant="secondary" type="submit">
                          비공개
                        </Button>
                      </form>
                    )}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="flex flex-col gap-3 md:hidden">
        {brackets.map((b) => (
          <div
            key={b.id}
            className="rounded-xl border border-matchon-border bg-white p-4 shadow-sm"
          >
            <div className="flex flex-wrap items-start justify-between gap-2">
              <BracketDivisionCell bracket={b} />
              <BracketStatusBadge status={b.status} />
            </div>
            <div className="flex flex-wrap gap-2">
              <BracketTypeBadge type={b.type} />
              <span className="text-muted-foreground text-xs">
                공개 {b.isPublic ? "예" : "아니오"} · 경기 {b.matchCount}
              </span>
            </div>
            <div className="flex flex-wrap gap-2">
              <Link
                href={`/organizer/events/${eventId}/brackets/${b.id}`}
                className={cn(buttonVariants({ variant: "outline", size: "sm" }))}
              >
                관리
              </Link>
              {!b.isPublic ? (
                <form action={publishBracketFormAction}>
                  <input type="hidden" name="bracketId" value={b.id} />
                  <Button size="sm" type="submit">
                    공개
                  </Button>
                </form>
              ) : (
                <form action={unpublishBracketFormAction}>
                  <input type="hidden" name="bracketId" value={b.id} />
                  <Button size="sm" variant="secondary" type="submit">
                    비공개
                  </Button>
                </form>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
